### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by altras** [ahdinosaur-deprecated/circles-api#1]
[circles-prototype] npm test                              21:23:27  ☁  master ☀

> circles.open.app@0.0.0 test /home/altras/development/circles-prototype
> npm run build && npm run build-test && mocha --recursive test
> 
> circles.open.app@0.0.0 build /home/altras/development/circles-prototype
> coffee -o lib -c src

sh: 1: coffee: not found

npm ERR! circles.open.app@0.0.0 build: `coffee -o lib -c src`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the circles.open.app@0.0.0 build script.
npm ERR! This is most likely a problem with the circles.open.app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     coffee -o lib -c src
npm ERR! You can get their info via:
npm ERR!     npm owner ls circles.open.app
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! cwd /home/altras/development/circles-prototype
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/altras/development/circles-prototype/npm-debug.log
npm ERR! not ok code 0
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

**Comment by ahdinosaur** [comment]
this error is resolved. :)
